#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Aug  9 14:42:43 2011

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Tool Bar
        self.toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_FLAT|wx.TB_DOCKABLE|wx.TB_3DBUTTONS|wx.TB_TEXT)
        self.SetToolBar(self.toolbar)
        self.toolbar.AddLabelTool(1, u"更新", wx.Bitmap("/Users/holbrook/Documents/workspace/commitassistant/gui/iphoneICONs/iphone-png 098.png", wx.BITMAP_TYPE_ANY), wx.Bitmap("/Users/holbrook/Documents/workspace/commitassistant/gui/iphoneICONs/iphone-png 098.png", wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "U", "Update")
        self.toolbar.AddLabelTool(2, u"打包", wx.Bitmap("/Users/holbrook/Documents/workspace/commitassistant/gui/iphoneICONs/iphone-png 049.png", wx.BITMAP_TYPE_ANY), wx.Bitmap("/Users/holbrook/Documents/workspace/commitassistant/gui/iphoneICONs/iphone-png 051.png", wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.mainGrid = wx.grid.Grid(self, -1, size=(1, 1))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle(u"Livebos提交助手")
        self.toolbar.SetToolBitmapSize((16, 15))
        self.toolbar.Realize()
        self.mainGrid.CreateGrid(10, 3)
        self.mainGrid.SetMinSize((716, 500))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.mainGrid, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MainFrame


class UpdateDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: UpdateDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_12 = wx.StaticText(self, -1, u"更新日期：")
        self.dateCtl = wx.DatePickerCtrl(self, -1)
        self.btnOK = wx.Button(self, wx.ID_OK, u"确定")
        self.label_13 = wx.StaticText(self, -1, u"更新时间：")
        self.timeCtl = wx.TextCtrl(self, -1, "00:00:00", style=wx.TE_CENTRE)
        self.btnCancel = wx.Button(self, wx.ID_CANCEL, u"取消")
        self.static_line_2 = wx.StaticLine(self, -1)
        self.doUpdate = wx.CheckBox(self, -1, u"执行svn update")
        self.label_14 = wx.StaticText(self, -1, u"xml目录：")
        self.xmlpathTxt = wx.TextCtrl(self, 11, "/Users/holbrook/Documents/svnroot/dev/JGXT/src/trunk/JGXT")
        self.btnXML = wx.Button(self, 1, "...")
        self.label_15 = wx.StaticText(self, -1, u"war目录：")
        self.warpathTxt = wx.TextCtrl(self, 12, "/Users/holbrook/Documents/svnroot/dev/JGXT/src/trunk/JGXT")
        self.btnWAR = wx.Button(self, 2, "...")
        self.label_16 = wx.StaticText(self, -1, u"doc目录：")
        self.docpathTxt = wx.TextCtrl(self, 13, "/Users/holbrook/Documents/svnroot/dev/JGXT/src/trunk/JGXT")
        self.btnDOC = wx.Button(self, 3, "...")
        self.label_17 = wx.StaticText(self, -1, u"sql目录：")
        self.sqlpathTxt = wx.TextCtrl(self, 14, "/Users/holbrook/Documents/svnroot/dev/JGXT/src/trunk/JGXT")
        self.btnSQL = wx.Button(self, 4, "...")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: UpdateDialog.__set_properties
        self.SetTitle(u"从svn获取更新")
        self.dateCtl.SetMinSize((100, 23))
        self.timeCtl.SetMinSize((100, 20))
        self.doUpdate.SetValue(1)
        self.xmlpathTxt.SetMinSize((400, 19))
        self.btnXML.SetMinSize((30, 20))
        self.warpathTxt.SetMinSize((400, 19))
        self.btnWAR.SetMinSize((30, 20))
        self.docpathTxt.SetMinSize((400, 19))
        self.btnDOC.SetMinSize((30, 20))
        self.sqlpathTxt.SetMinSize((400, 19))
        self.btnSQL.SetMinSize((30, 20))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: UpdateDialog.__do_layout
        grid_sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_6 = wx.FlexGridSizer(4, 3, 0, 0)
        grid_sizer_5 = wx.FlexGridSizer(2, 3, 0, 0)
        grid_sizer_5.Add(self.label_12, 0, 0, 0)
        grid_sizer_5.Add(self.dateCtl, 0, 0, 0)
        grid_sizer_5.Add(self.btnOK, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_5.Add(self.label_13, 0, 0, 0)
        grid_sizer_5.Add(self.timeCtl, 0, 0, 0)
        grid_sizer_5.Add(self.btnCancel, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_5.AddGrowableCol(2)
        grid_sizer_1.Add(grid_sizer_5, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND|wx.ALIGN_RIGHT, 10)
        grid_sizer_1.Add(self.static_line_2, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.doUpdate, 0, wx.TOP, 10)
        grid_sizer_6.Add(self.label_14, 0, 0, 0)
        grid_sizer_6.Add(self.xmlpathTxt, 0, 0, 0)
        grid_sizer_6.Add(self.btnXML, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_6.Add(self.label_15, 0, 0, 0)
        grid_sizer_6.Add(self.warpathTxt, 0, 0, 0)
        grid_sizer_6.Add(self.btnWAR, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_6.Add(self.label_16, 0, 0, 0)
        grid_sizer_6.Add(self.docpathTxt, 0, 0, 0)
        grid_sizer_6.Add(self.btnDOC, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_6.Add(self.label_17, 0, 0, 0)
        grid_sizer_6.Add(self.sqlpathTxt, 0, 0, 0)
        grid_sizer_6.Add(self.btnSQL, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_6.AddGrowableCol(2)
        grid_sizer_1.Add(grid_sizer_6, 1, wx.ALL|wx.EXPAND, 10)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class UpdateDialog


class PackageDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PackageDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PackageDialog.__set_properties
        self.SetTitle(u"打包（TODO）")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PackageDialog.__do_layout
        self.Layout()
        # end wxGlade

# end of class PackageDialog


class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        mainFrame = MainFrame(None, -1, "")
        self.SetTopWindow(mainFrame)
        mainFrame.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
